### ISSUE TITLE
Add support for aggregating results from multiple pipeline runs

### ISSUE THREAD

**Issue by armish** [hammerlab/epidisco#159] opened 2017-02-16 20:16 UTC
This would help users (like me) who run the pipeline for multiple patients and then do manual aggregation/collection of QC/variant-call results. What I have in mind is a subcommand that generates meta-report that provides links/info/summary when provided with paths of multiple pipeline results dir:

```bash
# Run multiple jobs
$ ocaml run_pipeline.ml pipeline ... --results-path $RESULTS_PATH -E Job1 ...
$ ocaml run_pipeline.ml pipeline ... --results-path $RESULTS_PATH -E Job2 ...
$ ocaml run_pipeline.ml pipeline ... --results-path $RESULTS_PATH -E Job3 ...
...

# and aggregate results as a single report on multiple runs
$ ocaml run_pipeline.ml aggregate \
       --input-results-path $RESULTS_PATH \
       --output-results-path $RESULTS_PATH/overview/
```

**Comment by smondet** [comment] 2017-02-16 20:25
Duplicate of https://github.com/hammerlab/epidisco/issues/4 but thanks for the UX suggestion.

**Closed as completed by smondet** 2017-02-16 20:25 UTC
Labels: enhancement
